
configure_dotfiles: true
configure_terminal: true
configure_jenv: true
configure_osx: false
homebrew_taps:
  - homebrew/cask-versions
dotfiles_files:
  - .gitconfig
  - .aliases
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .config
  - .colima
homebrew_cask_apps:
  - keybase
  - intellij-idea
  - amazon-chime
  - rectangle
  - dozer
  - alfred
  - virtualbox
  - little-snitch
  - dropbox
  - zoom
  - menumeters
  - wireshark
  - vagrant
  - cocoapods
  - alacritty
  - obsidian
  - vscodium
homebrew_installed_packages:
  - ruby
  - autoconf
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - sbt
  - ripgrep
  - maven
  - awscli
  - jq
  - gpg1
  - telnet
  - kafka
  - mackup
  - fd
  - hashicorp/tap/terraform
  - exercism
  - mkcert
  - nss
  - csvkit
  - graphviz
  - tmux
  - fzf
  - cmake
  - python
  - mono
  - go
  - vim
  - the_silver_searcher # ag grep search
  - carthage
  - nginx 
  - docker
  - docker-compose
  - colima
  - coreutils
  - mit-scheme # for sicp
homebrew_uninstalled_packages:
  - podman
  - amethyst
  - visual-studio-code
osx_script: "~/.osx --no-restart"
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 904280696,  name: "Things 3" }
  - { id: 411643860,  name: "DaisyDisk" }
dotfiles_repo: https://github.com/kadinvanvalin/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/github.com/kadinvanvalin/dotfiles
npm_packages: 
  - aws-cdk
  - cdktf-cli
  - "@cloudflare/wrangler"
  - yarn
  - tldr
gem_packages:
  - jekyll 
  - bundler
jenv_root: ~/.jenv
jenv_default_jdk: 16
jenv_jdks:
  - version: adoptopenjdk12
  - version: corretto
  - version: corretto8
configure_codium: true
codium_base_path: '~/Library/Application Support/VSCodium'
codium_config_path: "User"
codium_package_control:
  - "aaron-bond.better-comments"
  - "christian-kohler.path-intellisense"
  - "eamodio.gitlens"
  - "hashicorp.terraform"
  - "johnpapa.vscode-peacock"
  - "Orta.vscode-jest"
  - "scala-lang.scala"
  - "redhat.ansible"
  - "redhat.vscode-yaml"
  - "ms-toolsai.jupyter"
  - "ms-python.python"


