
configure_dotfiles: true
configure_terminal: true
configure_jenv: true
configure_osx: false
homebrew_taps:
  - homebrew/cask-versions
dotfiles_files:
  - .gitconfig
  - .aliases
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
homebrew_cask_apps:
  - keybase
  - intellij-idea
  - visual-studio-code
  - amazon-chime
  - rectangle
  - dozer
  - alfred
  - virtualbox
  - little-snitch
  - docker
  - dropbox
  - zoom
  - menumeters
  - wireshark
  - vagrant
  - cocoapods
  - amethyst
homebrew_installed_packages:
  - ruby
  - autoconf
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - sbt
  - ripgrep
  - maven
  - awscli
  - jq
  - gpg1
  - telnet
  - kafka
  - mackup
  - fd
  - hashicorp/tap/terraform
  - exercism
  - mkcert
  - nss
  - csvkit
  - graphviz
  - tmux
  - fzf
  - cmake
  - python
  - mono
  - go
  - vim
  - the_silver_searcher # ag grep search
  - carthage
  - nginx 
osx_script: "~/.osx --no-restart"
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 904280696,  name: "Things 3" }
  - { id: 411643860,  name: "DaisyDisk" }
dotfiles_repo: https://github.com/kadinvanvalin/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/github.com/kadinvanvalin/dotfiles
npm_packages: 
  - aws-cdk
  - cdktf-cli
  - "@cloudflare/wrangler"
  - yarn
  - tldr
gem_packages:
  - jekyll 
  - bundler
jenv_root: ~/.jenv
jenv_default_jdk: 16
jenv_jdks:
  - version: adoptopenjdk12
  - version: corretto
  - version: corretto8
