
configure_dotfiles: true
configure_terminal: true
# configure_jenv: true
configure_osx: false
homebrew_taps:
  - homebrew/cask-versions
  - helix-editor/helix
  - remotemobprogramming/brew
dotfiles_files: # loading all of these dotfiles from my repo
  - .gitconfig
  - .aliases
  - .zshrc
  - .gitignore
  - .inputrc
  - .vimrc
  - .config
  - .colima
  - .tmux.conf
  - .local
  - .amethyst.yml
  - .default-npm-packages
homebrew_cask_apps:
  - keybase # CJ uses this for secure communication
  - intellij-idea # CJ IDE
  - amazon-chime # AWS slack clone for communication with aws support
  - dozer # hides icons on the navbar
  - alfred # spotlight replacement
  - little-snitch # Paid app that monitors my network
  - dropbox # everyone knows what dropbox is, right?
  - zoom # maybe should remove - I use it VERY rarely 
  - menumeters # CPU and memory monitoring
  - wireshark # more traffic monitoring
  - vagrant 
  - cocoapods
  - obsidian # Markdown editor that I use for notes
  - vscodium # lighter weight IDE
  - contexts
  - 1password # lastpass is a good alternative - I should maybe host my own
  - alacritty # terminal replacement - warp breaks fzf
  - keycastr # for better pairing
  - whichspace # displays current space in top bar
  - amethyst # nice idea - but rectangle is easier to use
homebrew_cask_uninstalled_apps:
  - virtualbox # intel only for CJ
  - warp # terminal alternatice
  - visual-studio-code # using vscodium instead
  - rectangle # window manager
homebrew_installed_packages:
  - tmux # terminal multiplexer
  - starship # fancy prompt
  - ruby
  - autoconf
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - sbt
  - ripgrep
  - maven
  - awscli
  - jq
  - gpg1
  - telnet
  - kafka
  - fd
  - hashicorp/tap/terraform
  - exercism # cli for exercism. A coding exercise website
  - mkcert
  - nss
  - csvkit
  - graphviz
  - fzf
  - cmake
  - python
  - mono
  - go
  - vim
  - the_silver_searcher # ag grep search
  - carthage
  - nginx 
  - docker
  - docker-compose
  - docker-buildx
  - colima
  - coreutils
  - findutils # Collection of GNU find, xargs, and locate
  - thefuck # aliased to opps - that corrects errors in previous console commands
  - rustup-init
  - exa # ls and tree replacement
  - bat # cat replacement
  - zoxide # cd replacement
  - entr # Run arbitrary commands when files change
  - mob # tool for pairing and keeping git clean
homebrew_uninstalled_packages:
  - helix # using vim
  - zellij # terminal multiplexer - going back to tmux
  - mackup # maybe should uninstall - its for syncing preferences but ansible is doing that for me now
  - visualvm # All-in-One Java Troubleshooting Tool
  - midnight-commander # Terminal-based visual file manager
  - mit-scheme # for sicp book
  - podman # using colima instead
  - tree # replace with exa alias
  - yabai # window manager - unstable trying amethyst again
  - skhd # window manger helper? - unstable trying amethyst again
osx_script: "~/.osx --no-restart"
mas_installed_apps: # apps I pay for
  # - { id: 1333542190, name: "1Password" }
  - { id: 904280696,  name: "Things 3" } # todo list
  - { id: 411643860,  name: "DaisyDisk" }
dotfiles_repo: https://github.com/kadinvanvalin/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/github.com/kadinvanvalin/dotfiles
npm_packages: 
  - aws-cdk
  - cdktf-cli
  - "@cloudflare/wrangler"
  - yarn
  - tldr
gem_packages:
  # - jekyll 
  # - bundler
pip_packages:
  - boto3
  - botocore
  - jmespath
# jenv_root: ~/.jenv
# jenv_default_jdk: 16
# jenv_jdks:
#   - version: adoptopenjdk12
#   - version: corretto
#   - version: corretto8
configure_codium: true
codium_base_path: '~/Library/Application Support/VSCodium'
codium_config_path: "User"
codium_package_control:
  - "aaron-bond.better-comments"
  - "christian-kohler.path-intellisense"
  - "eamodio.gitlens"
  - "hashicorp.terraform"
  - "johnpapa.vscode-peacock"
  - "Orta.vscode-jest"
  - "scala-lang.scala"
  - "redhat.ansible"
  - "redhat.vscode-yaml"
  - "ms-toolsai.jupyter"
  - "ms-python.python"
  - "vscodevim.vim"
asdf_plugins:
  - name: "nodejs"        
    environment: {} # an optional dictionary of environment variables for build configuration
    versions:
      - lts-gallium
    global: lts-gallium    # set as a global version, optional
  - name: "java"  
    versions:
      - corretto-17.0.2.8.1
      - corretto-8.322.06.1
    global: corretto-17.0.2.8.1 
