---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: jenv
    src: git+https://github.com/EiyuuZack/ansible-role-jenv.git

collections:
  - name: geerlingguy.mac
