---
- name: create cron to push notebook every 15 minutes
  ansible.builtin.cron:
    name: notebook autoupdate
    weekday: "*"
    minute: "*/15"
    hour: "*"
    user: "{{ ansible_user_id }}"
    job: "cd ~/github.com/kadinvanvalin/notes; git wip"


