---
- name: Ensure docker cli directory exists.
  file:
    path: "~/.docker/cli-plugins"
    state: directory
- name: Create symlink for docker compose docker cli directory exists.
  file:
    src: "/usr/local/bin/docker-compose"
    dest: "~/.docker/cli-plugins/docker-compose"
    state: link
- name: Create symlink for docker buildx docker cli directory exists.
  file:
    src: "/usr/local/bin/docker-buildx"
    dest: "~/.docker/cli-plugins/docker-buildx"
    state: link
- name: set buildx as default builder
  ansible.builtin.command: docker buildx install   
