---
- name: Ensure can sudo with touchid
  become: true
  blockinfile:
    name: '/etc/pam.d/sudo'
    create: no
    insertbefore: BOF
    block: |
      # allow touchid
      auth sufficient pam_tid.so