---
- name: Ensure .vim/{autoload,bundle,undodir} directory exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/undodir"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"
- name: Ensure Plug is in place
  get_url:
    dest: "{{ vim_dir }}/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
- name: Install Vim plugins
  git:
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
    - name: morhetz/gruvbox
      url: https://github.com/morhetz/gruvbox.git
    - name: YCM
      url: https://github.com/ycm-core/YouCompleteMe
     