---
- name: Ensure .zsh directory exists
  file:
    path: "~/.zsh"
    state: directory
    recurse: no
    mode: 0750
- name: Clone zsh-autocomplete
  git:
    dest: "~/.zsh/zsh-autocomplete"
    repo: "https://github.com/marlonrichert/zsh-autocomplete.git"
    clone: yes
    depth: 1
- name: Clone fzf-tab
  git:
    dest: "~/.zsh/fzf-tab"
    repo: "https://github.com/Aloxaf/fzf-tab.git"
    clone: yes
    depth: 1
- name: Clone zsh-autosuggestions
  git:
    dest: "~/.zsh/zsh-autosuggestions"
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    clone: yes
    depth: 1